#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Feb 20 19:01:28 MSK 2023
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 59e48327845d485a991abf49c9e085ef --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot BCD_2_BIN_test_behav xil_defaultlib.BCD_2_BIN_test xil_defaultlib.glbl -log elaborate.log"
xelab -wto 59e48327845d485a991abf49c9e085ef --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot BCD_2_BIN_test_behav xil_defaultlib.BCD_2_BIN_test xil_defaultlib.glbl -log elaborate.log

