webtalk_init -webtalk_dir /home/leonid/Desktop/university/year3/DigitalCircuitry/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/my_func_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Apr 17 19:56:42 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "dbed0831-243e-4489-a5ff-b7c48dd691b2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "d69f94fe10f342b9bdadc43ab1856086" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "391" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 22.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3737.695 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "4 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "119188_KB" -context "xsim\\usage"
webtalk_transmit -clientid 199792561 -regid "" -xml /home/leonid/Desktop/university/year3/DigitalCircuitry/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/my_func_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/leonid/Desktop/university/year3/DigitalCircuitry/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/my_func_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/leonid/Desktop/university/year3/DigitalCircuitry/lab2/lab2.sim/sim_1/behav/xsim/xsim.dir/my_func_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
