// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module next_set (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        permutations_address0,
        permutations_ce0,
        permutations_we0,
        permutations_d0,
        permutations_q0,
        permutations_address1,
        permutations_ce1,
        permutations_we1,
        permutations_d1,
        permutations_q1,
        ap_return
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] permutations_address0;
output   permutations_ce0;
output   permutations_we0;
output  [31:0] permutations_d0;
input  [31:0] permutations_q0;
output  [2:0] permutations_address1;
output   permutations_ce1;
output   permutations_we1;
output  [31:0] permutations_d1;
input  [31:0] permutations_q1;
output  [0:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[2:0] permutations_address0;
reg permutations_ce0;
reg permutations_we0;
reg[2:0] permutations_address1;
reg permutations_ce1;
reg permutations_we1;
reg[0:0] ap_return;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_131;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state8;
reg   [2:0] permutations_addr_reg_219;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln53_fu_137_p2;
wire   [31:0] j_fu_165_p2;
wire   [0:0] icmp_ln53_1_fu_159_p2;
wire  signed [31:0] k_fu_171_p2;
reg  signed [31:0] k_reg_238;
wire    ap_CS_fsm_state4;
reg   [2:0] permutations_addr_2_reg_243;
wire  signed [31:0] l_fu_188_p2;
reg  signed [31:0] l_reg_251;
wire    ap_CS_fsm_state7;
reg   [2:0] permutations_addr_3_reg_259;
wire   [0:0] icmp_ln60_fu_194_p2;
reg   [2:0] permutations_addr_4_reg_264;
wire   [31:0] add_ln61_fu_210_p2;
reg   [31:0] add_ln61_reg_269;
reg  signed [31:0] i_assign_reg_74;
reg   [31:0] k_0_in_reg_86;
wire    ap_CS_fsm_state5;
wire   [0:0] icmp_ln57_fu_182_p2;
reg  signed [31:0] r_reg_97;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state9;
reg   [31:0] l_0_in_reg_108;
reg   [0:0] p_0_reg_118;
wire  signed [63:0] sext_ln53_fu_143_p1;
wire  signed [63:0] sext_ln53_1_fu_154_p1;
wire  signed [63:0] sext_ln57_fu_177_p1;
wire  signed [63:0] sext_ln46_fu_200_p1;
wire  signed [63:0] sext_ln47_fu_205_p1;
wire   [31:0] add_ln53_fu_148_p2;
reg   [0:0] ap_return_preg;
wire    ap_CS_fsm_state10;
reg   [9:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
#0 ap_return_preg = 1'd0;
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_return_preg <= 1'd0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            ap_return_preg <= p_0_reg_118;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_1_fu_159_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        i_assign_reg_74 <= j_fu_165_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        i_assign_reg_74 <= 32'd4294967294;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_1_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        k_0_in_reg_86 <= 32'd0;
    end else if (((icmp_ln57_fu_182_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        k_0_in_reg_86 <= k_reg_238;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        l_0_in_reg_108 <= l_reg_251;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        l_0_in_reg_108 <= i_assign_reg_74;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_137_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        p_0_reg_118 <= 1'd0;
    end else if (((icmp_ln60_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        p_0_reg_118 <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        r_reg_97 <= add_ln61_reg_269;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        r_reg_97 <= 32'd4294967295;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        reg_131 <= permutations_q1;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        reg_131 <= permutations_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln60_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        add_ln61_reg_269 <= add_ln61_fu_210_p2;
        permutations_addr_3_reg_259 <= sext_ln46_fu_200_p1;
        permutations_addr_4_reg_264 <= sext_ln47_fu_205_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        k_reg_238 <= k_fu_171_p2;
        permutations_addr_2_reg_243 <= sext_ln57_fu_177_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        l_reg_251 <= l_fu_188_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_137_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        permutations_addr_reg_219 <= sext_ln53_fu_143_p1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state10) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ap_return = p_0_reg_118;
    end else begin
        ap_return = ap_return_preg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        permutations_address0 = permutations_addr_4_reg_264;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        permutations_address0 = sext_ln47_fu_205_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        permutations_address0 = permutations_addr_2_reg_243;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        permutations_address0 = sext_ln57_fu_177_p1;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        permutations_address0 = sext_ln53_fu_143_p1;
    end else begin
        permutations_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        permutations_address1 = permutations_addr_3_reg_259;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        permutations_address1 = sext_ln46_fu_200_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        permutations_address1 = permutations_addr_reg_219;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        permutations_address1 = sext_ln53_1_fu_154_p1;
    end else begin
        permutations_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state6))) begin
        permutations_ce0 = 1'b1;
    end else begin
        permutations_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5))) begin
        permutations_ce1 = 1'b1;
    end else begin
        permutations_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state6))) begin
        permutations_we0 = 1'b1;
    end else begin
        permutations_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state8) | ((icmp_ln57_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5)))) begin
        permutations_we1 = 1'b1;
    end else begin
        permutations_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln53_fu_137_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln53_1_fu_159_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            if (((icmp_ln57_fu_182_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln60_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln53_fu_148_p2 = ($signed(i_assign_reg_74) + $signed(32'd1));

assign add_ln61_fu_210_p2 = ($signed(r_reg_97) + $signed(32'd4294967295));

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign icmp_ln53_1_fu_159_p2 = (($signed(permutations_q0) < $signed(permutations_q1)) ? 1'b1 : 1'b0);

assign icmp_ln53_fu_137_p2 = ((i_assign_reg_74 == 32'd4294967295) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_182_p2 = (($signed(reg_131) < $signed(permutations_q0)) ? 1'b1 : 1'b0);

assign icmp_ln60_fu_194_p2 = (($signed(l_fu_188_p2) < $signed(r_reg_97)) ? 1'b1 : 1'b0);

assign j_fu_165_p2 = ($signed(i_assign_reg_74) + $signed(32'd4294967295));

assign k_fu_171_p2 = ($signed(k_0_in_reg_86) + $signed(32'd4294967295));

assign l_fu_188_p2 = (l_0_in_reg_108 + 32'd1);

assign permutations_d0 = reg_131;

assign permutations_d1 = permutations_q0;

assign sext_ln46_fu_200_p1 = l_fu_188_p2;

assign sext_ln47_fu_205_p1 = r_reg_97;

assign sext_ln53_1_fu_154_p1 = $signed(add_ln53_fu_148_p2);

assign sext_ln53_fu_143_p1 = i_assign_reg_74;

assign sext_ln57_fu_177_p1 = k_fu_171_p2;

endmodule //next_set
