( defvar a " h " )
( defvar b " e " )
( defvar c " l " )
( defvar d " l " )
( defvar e " o " )
( defvar f " " )
( defvar g " w " )
( defvar h " o " )
( defvar i " r " )
( defvar j " l " )
( defvar k " d " )

( format t a )
( format t b )
( format t c )
( format t d )
( format t e )
( format t f )
( format t g )
( format t h )
( format t i )
( format t j )
( format t k )